### ISSUE TITLE
The engine "node" is incompatible with this module.

### ISSUE THREAD

**Issue by NickEmpetvee** [creativetimofficial/material-kit-react#102]
### Version
2.0.0
### Reproduction link
https://not.applicable
### Operating System
Win 10
### Device
PC
### Browser & Version
Chrome 100.0.4896.127
### Steps to reproduce
1. Download the product and unzip
2. CD to the root directory
3. Run `yarn install`
### What is expected?
Expected result: node_modules builds with the versions specified in package.json.
### What is actually happening?
Actual result: An error message is returned saying this version of material-kit-react is incompatible with the Node.js version (17.4). 17.4 is current. Here is the error:

```
C:\mcdev\react\material-kit-react-main>yarn install
yarn install v1.22.5
info No lockfile found.
[1/5] Validating package.json...
error material-kit-2-react@2.0.0: The engine "node" is incompatible with this module. Expected version "14 || 15 || 16". Got "17.4.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

`npm -install` fails as well.

---
### Solution
None. I need node 17+ which is current for other reasons in this ecosystem. Is there a roadmap for making this package compliant?
### Additional comments
Thank you. I'm greatly looking forward to using one of your React / Material templates!

**Comment by sajadevo** [comment]
> ### Version
> 2.0.0
> 
> ### Reproduction link
> https://not.applicable
> 
> ### Operating System
> Win 10
> 
> ### Device
> PC
> 
> ### Browser & Version
> Chrome 100.0.4896.127
> 
> ### Steps to reproduce
> 1. Download the product and unzip
> 2. CD to the root directory
> 3. Run `yarn install`
> 
> ### What is expected?
> Expected result: node_modules builds with the versions specified in package.json.
> 
> ### What is actually happening?
> Actual result: An error message is returned saying this version of material-kit-react is incompatible with the Node.js version (17.4). 17.4 is current. Here is the error:
> 
> ```
> C:\mcdev\react\material-kit-react-main>yarn install
> yarn install v1.22.5
> info No lockfile found.
> [1/5] Validating package.json...
> error material-kit-2-react@2.0.0: The engine "node" is incompatible with this module. Expected version "14 || 15 || 16". Got "17.4.0"
> error Found incompatible module.
> info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
> ```
> 
> `npm -install` fails as well.
> 
> ### Solution
> None. I need node 17+ which is current for other reasons in this ecosystem. Is there a roadmap for making this package compliant?
> 
> ### Additional comments
> Thank you. I'm greatly looking forward to using one of your React / Material templates!

**Hi @NickEmpetvee**

Thanks for using our product, please remove the engine scripts from the package.json file and it will work fine.

**Note: To get the latest updates and supports for the products and other related things to Creative Tim please join our [Discord Community](https://discord.gg/7xzMRsRebr).**

**All the best,
Sajad 
React Developer @ [Creative-Tim.com](http://creative-tim.com/)**

**Comment by NickEmpetvee** [comment]
HI @sajadevo,

Thank you.
