### ISSUE TITLE
a small bug

### ISSUE THREAD

**Issue by mohamadrezahedayat** [creativetimofficial/material-kit-react#104]
src/pages/LandingPages/AboutUs/sections/Newsletter.js in line 35-->
<Grid item sx={12} md={6} sx={{ ml: { xs: 0, lg: 3 }, mb: { xs: 12, md: 0 } }}>
sx={12} is wrong ----> xs={12}
thank you

**Comment by sajadevo** [comment]
**Hi @mohamadrezahedayat**

Thanks for helping us to find and fix the issue for our products, I really appreciate it.

**Note: To get the latest updates and supports for the products and other related things to Creative Tim please join our [Discord Community](https://discord.gg/7xzMRsRebr).**

**All the best,
Sajad 
React Developer @ [Creative-Tim.com](http://creative-tim.com/)**
