### ISSUE TITLE
Component npm module?

### ISSUE THREAD

**Issue by raymondsze** [creativetimofficial/material-kit-react#13]
Awesome work! I love the components design.
Do you plan to publish the components as separate modules that I could use together with material-ui v1.0?
Love to see if there is a plan for Typescript support as well.

**Comment by EINazare** [comment]
Hello @raymondsze ,

Thank you for your interest in using our product.
We aren't going to publish separate components on npm unfortunately, there is to much work to do this and maintain the packages, and we have some other projects that we are working on.
As for Typescript, we do not have in plan to support it as of moment, once again, we have some other projects that we are working on that aren't leaving us to much time for anything else. In the past, some of our users have requested this as well, so when we are going to have some spare time, we are definitively going to take a look at this.

Best,
Manu
