### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by softmarshmallow** [creativetimofficial/material-kit-react#15]
is this for demo? or can i add it on existing material-ui-next.com based project?

**Comment by EINazare** [comment]
Hello @softmarshmallow ,

Thank you for your interest in using our product.
Since this is a free open source product, you can use it how you want.

Best,
Manu

**Comment by nd2s** [comment]
@EINazare Not sure if @softmarshmallow  meant it like that, but: Can one just use these components as a library? I only seem to be able to copy/use the files directly, which makes maintenance/updates almost impossible.

**Comment by EINazare** [comment]
Hello @nd2s ,

I am sorry if i misunderstood what this question was.
I've added it on npmjs - [right here](https://www.npmjs.com/package/material-kit-react) - but not sure how you would use it.
Right now, i am working on some other stuff (other products) that have a little bit more priority and cannot make tests to see how to correctly upload it on npmjs.
Any suggestions would be much appreciated.

Best,
Manu

**Comment by bader-ht** [comment]
Hello.  We're loving the look of this template, but are not having much luck adding the styled components to an existing project.  All the import statements seem to fail (even after 'npm install --g cross-env' and modifying the start scripts command).  Can you guide us as to how the components can be used in an existing project?

**Comment by bader-ht** [comment]
Hello @EINazare, 

I've downloaded the source from the repository.

**Comment by EINazare** [comment]
Hello again @bader-ht ,

I didn't think about asking you this in my last comment, but are you using `webpack` ?

Best,
Manu

**Comment by shanekoss** [comment]
@EINazare is there documentation about how to import these components into an existing project or do you have start from scratch?  thanks!

**Comment by EINazare** [comment]
Hello there, @shanekoss ,

Please read this: https://github.com/creativetimofficial/ct-material-dashboard-pro-react/issues/50#issuecomment-407030675

Best,
Manu
