### ISSUE TITLE
DateTimePicker not fully match the theme

### ISSUE THREAD

**Issue by romannep** [creativetimofficial/material-kit-react#20]
DateTimePicker as described in documentation not fully match the theme: floating label are not the same size and it behavior not like in CustomInput.

But `react-datetime` support custom input render, so we can pass CustomInput to it.

Consider another implementation:
````
import React from 'react';
import Datetime from 'react-datetime';

import CustomInput from 'material-kit-react/...;

const DateTimePicker = (props) => {
  const {
    inputProps: { onBlur, onFocus, value, onChange, ...restInputProps },
    formControlProps,
    labelText,
    ...restProps
  } = props;
  return (
    <Datetime
      onFocus={onFocus}
      onBlur={onBlur}
      value={value}
      onChange={onChange}
      renderInput={(dateInputProps, open, close) => (
        <CustomInput
          inputProps={{ ...dateInputProps, ...restInputProps }}
          onBlur={close}
          onFocus={open}
          labelText={labelText}
          formControlProps={formControlProps}
        />
      )}
      {...restProps}
    />
  );
};
````
with corrected style
````
.rdt.rdtOpen .rdtPicker {
  margin-top: 24px;
}
````

**Comment by EINazare** [comment]
Hello @romannep ,

Thank you for this, we are going to make some tests for our next update, and if everything works fine, than we'll definitely add this to our code.

Once again thank you,
Manu

**Comment by Cypox71** [comment]
Waiting for update... I'm exeriencing same wrong behavior

Thanks
Frank

**Comment by EINazare** [comment]
Hello there @Cypox71 ,

Our board decided to leave the product as is, and this to only be a feature that our clients can add if they want to do so.

Best,
Manu

**Comment by dandin84** [comment]
Hi,

Inspired by @romannep here is my implementation for the latest "react-datetime" & "Material Dashboard PRO React" versions:

import React from "react";
import PropTypes from "prop-types";
import DateTime from "react-datetime";
import "react-datetime/css/react-datetime.css";
import CustomInput from "components/CustomInput/CustomInput";
import moment from "moment";

export default function DatePicker(props) {
  const {
    inputProps: { value, onChange, name, ...restInputProps },
    formControlProps,
    labelText,
    ...restProps
  } = props;

  return (
    <>
      <DateTime
        value={value}
        timeFormat={false}
        onChange={(date) => {
          onChange(date);
        }}
        closeOnSelect={true}
        renderInput={(dateInputProps, open) => (
          <CustomInput
            inputProps={{
              ...dateInputProps,
              ...restInputProps,
              onFocus: open,
              name: name,
              value: value ? moment(value).format("DD/MM/YYYY") : "",
            }}
            labelText={labelText}
            formControlProps={formControlProps}
          />
        )}
        {...restProps}
      />
    </>
  );
}

DatePicker.propTypes = {
  labelText: PropTypes.string,
  formControlProps: PropTypes.object,
  inputProps: PropTypes.object,
};

Inspired by https://stackoverflow.com/a/64972324
The line "value: value ? moment(value).format("DD/MM/YYYY") : "","

**Comment by sajadevo** [comment]
**Hi there**

We've updated the product to v2.0.0 and now it contains a totally new structure with a new and fresh design.

**All the best**
**Sajad**
