### ISSUE TITLE
Routes in header

### ISSUE THREAD

**Issue by virazura** [creativetimofficial/material-kit-react#22]
I'm having trouble to use the route in headerlink, I changed the headerlink component to this

`function HeaderLinks({ ...props }) {
  const { classes } = props;
  return (
    <List className={classes.list}>
      <ListItem className={classes.listItem}>
        <Link to="/about" exact>
        <Button
            color="transparent" 
            className={classes.navLink}
          >
              {props.navLink1}
          </Button>
        </Link>`

and add the code inside index.jsx
`import SectionAbout from "views/Components/Sections/SectionAbout.jsx";
{ path: "/about  exact", name: "About", component: SectionAbout },
`

and here's header component inside components views looks like

`<Header
          brand="Novel-ist"
          rightLinks={<HeaderLinks 
            navLink1="About" />}
          fixed
          color="transparent"
          changeColorOnScroll={{
            height: 400,
            color: "montecarlo"
          }}
          {...rest}
        />`

can i put the link inside the header component or is there any way to put the the link in navigation bar?

**Comment by EINazare** [comment]
Hello @virazura ,

And thank you for your interest in using our product.
I think you can put the link directly in the Header if you want, or in the HeaderLinks, it is up to you.

Best,
Manu

**Comment by virazura** [comment]
how about use the router in the same page? like in components view page there's multiple section how to jump from one section to another

**Comment by EINazare** [comment]
Hello again @virazura ,

I do not understand where you want to use in the same page the router.
I have a strange feeling that you want to learn react with our product. Is this right?

Best,
Manu

**Comment by virazura** [comment]
what i meant is hash link, but nevermind already figure it out. by the way thanks for the product so helpful :)
