### ISSUE TITLE
npm  start

### ISSUE THREAD

**Issue by MikeIsAnAsset** [creativetimofficial/material-kit-react#23]
I have tried to start and I have followed the suggestions on https://demos.creative-tim.com/material-kit-react/#/documentation/tutorial.  Here is the error I get no matter which suggesstion I follow:

'NODE_PATH' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! material-kit-react@1.1.0 start: `NODE_PATH=./src npm-run-all -p watch-css start-js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the material-kit-react@1.1.0 start script.

**Comment by EINazare** [comment]
Dupe #9
