### ISSUE TITLE
Paths are missing ../../

### ISSUE THREAD

**Issue by MikeIsAnAsset** [creativetimofficial/material-kit-react#24]
I am still trying to overcome compile errors for wrong paths so far starting with assets or components.  I have had to put ../../ or ../../../ or ../../../../ or ../../../../../ to make them work.  There are so many of them I still haven't yet started the app since I downloaded, so I can't wait until all these compile errors are overcome so i can actually see what this app is like.

**Comment by kdclaw3** [comment]
Hey @MikeIsAnAsset I believe this project was created using "create-react-app" and it looks like you might be using something else to transpile the app? If you are using babel you can use babel-plugin-module-resolver and just add something like:
```		
["module-resolver", {
	"root": ["./client/src"]
}]
```
to the .bablerc file. Take a look at https://github.com/kdclaw3/earth_rocker_project_boilerplate I've put in some sample webpack/babel configuration that you should be able to use to get the project to work.

**Comment by kdclaw3** [comment]
Hey @MikeIsAnAsset if you are not using babel take a look at the notes from here they might help you out as well https://github.com/creativetimofficial/material-dashboard-react/issues/20

**Comment by MikeIsAnAsset** [comment]
I have been able to start the project after making those changes.
