### ISSUE TITLE
You should not use <Link> outside a <Router>, material-kit-react/src/components/Header/HeaderLinks.jsx

### ISSUE THREAD

**Issue by kdclaw3** [creativetimofficial/material-kit-react#25]
You should not use ```<Link>``` outside a ```<Router>```

material-kit-react/src/components/Header/HeaderLinks.jsx

**Comment by EINazare** [comment]
Hello @kdclaw3 ,

And thank you for your interest in our product.
We have a Router inside the `src/index.js`, in which then we render the rest of our components, so the Link from HeaderLinks is inside a router.
Is this an error that you get?

Best,
Manu

**Comment by EINazare** [comment]
Hello again @kdclaw3 ,

Is this still an issue?

Best,
Manu
