### ISSUE TITLE
Missing, and out of date dependencies

### ISSUE THREAD

**Issue by kdclaw3** [creativetimofficial/material-kit-react#26]
Quite a few dependencies are missing to get the project to work out of the box

**Missing**
prop-types
classnames
react-router

**Missing and Out of Date**
react-popper (also note it must be installed at v0.10.4, the project will not support current 1.0 version)

**Comment by EINazare** [comment]
Hello again @kdclaw3 ,

We did not add those dependencies since they come with `npm install`, but you are right, we should add them and we'll do so on our next update.

Best,
Manu
