### ISSUE TITLE
Change word "built" to "build"

### ISSUE THREAD

**Issue by Beamanator** [creativetimofficial/material-kit-react#28]
https://github.com/creativetimofficial/material-kit-react/blob/b3e48d3b9fd5e9210fe97be004c6503dd62bc1ed/src/views/Components/Sections/SectionCompletedExamples.jsx#L25

Just being picky, sorry.

**Comment by EINazare** [comment]
Hello @Beamanator ,

Thank you for your interest in using our product and for pointing our this issue.
I believe next week or the following weeks we are going to make some updates to our material products and we are going to solve this issue as well.
Please do not close it yet.

Best,
Manu
