### ISSUE TITLE
👋 Some notes I took looking at the source code :)

### ISSUE THREAD

**Issue by oliviertassinari** [creativetimofficial/material-kit-react#3]
Hi 👋 ,

I have been browsing most of the components. I'm very happy to see this themed version of Material-UI! Great job. I have gathered some notes looking at the source code:
- I'm not sure to see why it's important. Maybe saying it's React related?
https://github.com/creativetimofficial/material-kit-react/blob/b4e19120e8bb86d9458c956447a150292aff027e/src/components/Badge/Badge.jsx#L2
- No need to destructure the props
https://github.com/creativetimofficial/material-kit-react/blob/b4e19120e8bb86d9458c956447a150292aff027e/src/components/Badge/Badge.jsx#L10
[Babel will transpile it](https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=usage&code_lz=GYVwdgxgLglg9mABAIQIYBMDmBTAFAb0QDoSAHAJzlIGdEBfASkXwChFEIFqpmOAbVNWrZqAGg5w-ccuIgALGH3TlsSOogC8iClWoBuNohVQQ5JLkPsAPNVKokEAUIByqALbYN-R4OHUiAEYYOIgA1IgARJFh_L4iANqcUuQAunQAfN4KSipgdFYA9Lb26YYMBnQsQA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&lineWrap=false&presets=es2015%2Creact%2Cstage-0&prettier=false&targets=&version=6.26.0&envVersion=1.6.2), it's not free.
- You can shorten the `[className]: className !== undefined` pattern:
https://github.com/creativetimofficial/material-kit-react/blob/b4e19120e8bb86d9458c956447a150292aff027e/src/components/Card/CardBody.jsx#L15-L18
```jsx
 const cardBodyClasses = classNames({ [classes.cardBody]: true }, className); 
```
- Something, using the `classes` API over the `className` can save LoC.
However, in order to be efficient, the parent child keys much match the children style key you want to override. 
- If you want to allow full customization of top of this theme, better take the habite of spreading the `rest` after rather than before the other properties:
https://github.com/creativetimofficial/material-kit-react/blob/b4e19120e8bb86d9458c956447a150292aff027e/src/components/CustomButtons/IconButton.jsx#L11-L12
- Nice composed component 👍 
https://github.com/creativetimofficial/material-kit-react/blob/b4e19120e8bb86d9458c956447a150292aff027e/src/components/CustomDropdown/CustomDropdown.jsx#L22
- I think that it would  be better to use the `ref` property to get a reference on the root element rather than using this logic. You might have different header in the page, who knows.
https://github.com/creativetimofficial/material-kit-react/blob/b4e19120e8bb86d9458c956447a150292aff027e/src/components/Header/Header.jsx#L40-L41
We use https://github.com/mui-org/material-ui/blob/f64c730a3faacd39ce3977b6a9d058a208446d82/packages/material-ui/src/internal/RootRef.js from time to time. Maybe we can make it public, but at least, I hope you get the idea.
- https://github.com/creativetimofficial/material-kit-react/blob/b4e19120e8bb86d9458c956447a150292aff027e/src/components/Footer/Footer.jsx#L57
Why don't you use `.getFullYear()`, isn't `.getYear()` *deprecated*?

Keep the good work :)

**Comment by unmonk** [comment]
Also noticed SCSS is named _bootstrap.

I am a little confused as to why we have scss dependencies, but you also have JSS, and Material does its own styling.   

Is this left over boilerplate?

**Comment by EINazare** [comment]
Hello guys,

Thank you for this feedback. 
You help us make our products better.
@unmonk , we have those dependencies for the plugins that we are using (plugins that do no come with jss).
@oliviertassinari thank you for all of those points.
We are going to make changes / make an updated after Material-UI will be released on the stable v1.0.0. I've seen that you plan to release it on May 17th, and we are going to update our products then.

Thanks again for your feedback,
Manu

**Comment by nd2s** [comment]
Any news on that stable update?

**Comment by EINazare** [comment]
Hello @nd2s ,

Yes, we started the work on the stable version for the [material-dashboard-pro-react](https://demos.creative-tim.com/material-dashboard-pro-react/?_ga=2.58569513.2016648865.1528091762-329288944.1519374311#/dashboard)  product, after that we are going to make an update on [material-dashboard-react](https://demos.creative-tim.com/material-dashboard-react/?_ga=2.58569513.2016648865.1528091762-329288944.1519374311#/dashboard) and after that on [material-kit-react](https://demos.creative-tim.com/material-kit-react/?_ga=2.58569513.2016648865.1528091762-329288944.1519374311#/). I think maybe next week will be done, but i do not promise anything. We move as fast as we can.

Best,
Manu

**Comment by oliviertassinari** [comment]
@EINazare Hey Nazare, can I have a bit more context around this "lag"? Maybe you could send me a reproduction so I can have a look at it?

**Comment by EINazare** [comment]
@oliviertassinari ,

Is it ok if we move this conversation on email?

Manu

**Comment by oliviertassinari** [comment]
Perfect
