### ISSUE TITLE
Stop button shadow after not hovered and focused

### ISSUE THREAD

**Issue by Sebastian-Nielsen** [creativetimofficial/material-kit-react#31]
I am refering to these buttons: https://demos.creative-tim.com/material-kit-react/?_ga=2.117141381.2087365620.1533070297-784988714.1532690153#/

Try and click on one of them, drag the mouse away, and watch how it still has the shadow underneath indicating that it is either hovered or focused or both. 

Can this be removed? So that the shadow effect disappears when the button is not hovered or focused?

**Comment by EINazare** [comment]
Hello @Sebastian-Nielsen ,

And thank you for your interest in using our product.
Sorry for this late response, we've had some free days.
This comes from the focus css/jss rule, and we've added it so we can override the default style from material-ui. You can delete it , but it would look really stupid (it would have a grey box-shadow).
You can change all the jss, and make that on focus, the box-shadow to be the same as the one that is on normal button.
For example (please keep in mind that you need to do this to all buttons) you have to make the following changes for the primary button inside `src/assets/jss/material-kit-react/components/buttonStyle.jsx`:
From
```
primary: {
    backgroundColor: primaryColor,
    boxShadow:
      "0 2px 2px 0 rgba(156, 39, 176, 0.14), 0 3px 1px -2px rgba(156, 39, 176, 0.2), 0 1px 5px 0 rgba(156, 39, 176, 0.12)",
    "&:hover,&:focus": {
      backgroundColor: primaryColor,
      boxShadow:
        "0 14px 26px -12px rgba(156, 39, 176, 0.42), 0 4px 23px 0px rgba(0, 0, 0, 0.12), 0 8px 10px -5px rgba(156, 39, 176, 0.2)"
    }
  },
```
To
```
primary: {
    "&:hover,&:hover:focus": {
      backgroundColor: primaryColor,
      boxShadow:
        "0 14px 26px -12px rgba(156, 39, 176, 0.42), 0 4px 23px 0px rgba(0, 0, 0, 0.12), 0 8px 10px -5px rgba(156, 39, 176, 0.2)"
    },
    "&,&:focus": {
      backgroundColor: primaryColor,
      boxShadow:
        "0 2px 2px 0 rgba(156, 39, 176, 0.14), 0 3px 1px -2px rgba(156, 39, 176, 0.2), 0 1px 5px 0 rgba(156, 39, 176, 0.12)",
    }
  },
```
Hope that information helps you. Please let us know if we can help you with anything else.

Best,
Manu
