### ISSUE TITLE
Module not found: Can't resolve '@babel/runtime/helpers/builtin/assertThisInitialized'

### ISSUE THREAD

**Issue by chayakornwc** [creativetimofficial/material-kit-react#32]
./node_modules/@material-ui/core/ButtonBase/ButtonBase.js
Module not found: Can't resolve '@babel/runtime/helpers/builtin/assertThisInitialized' in '~/node_modules/@material-ui/core/ButtonBase'

how to resolve about that

**Comment by tarcisiopqdt** [comment]
I have the same problem

**Comment by Den-web** [comment]
I have the same problem

**Comment by EINazare** [comment]
Hello guys,

You can find the solution here: [https://github.com/creativetimofficial/ct-material-dashboard-pro-react/issues/62](https://github.com/creativetimofficial/ct-material-dashboard-pro-react/issues/62)

Best,
Manu

**Comment by chayakornwc** [comment]
Hello everyone, i solve by change  dependencies ->  "@material-ui/core": "1.4.3" and  "react-popper": "0.10.4", 

my package json 

`
{
  "name": "material-kit-react",
  "version": "1.1.0",
  "private": true,
  "dependencies": {
    "@material-ui/core": "1.4.3",
    "@material-ui/icons": "1.1.0",
    "ajv": "6.0.0",
    "history": "4.7.2",
    "moment": "2.22.2",
    "node-sass-chokidar": "1.3.0",
    "npm-run-all": "4.1.3",
    "react": "16.4.0",
    "react-datetime": "2.14.0",
    "react-dom": "16.4.0",
    "react-nouislider": "2.0.1",
    "react-popper": "0.10.4",
    "react-router-dom": "4.3.1",
    "react-scripts": "1.1.4",
    "react-slick": "0.23.1",
    "react-swipeable-views": "0.12.13"
  },
  "scripts": {
    "build-css": "node-sass-chokidar --include-path ./src --include-path ./node_modules src/ -o src/",
    "watch-css": "npm run build-css && node-sass-chokidar --include-path ./src --include-path ./node_modules src/ -o src/ --watch --recursive",
    "start-js": "react-scripts start",
    "start": "npm-run-all -p watch-css start-js",
    "build": "npm run build-css && react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  }
}

`
