### ISSUE TITLE
Cannot fully change the primary color.

### ISSUE THREAD

**Issue by Sedim** [creativetimofficial/material-kit-react#4]
I can change the primary color Purple to another color such as  Navy blue "#2f2fab" in material-kit-react.jsx 
from:
`const primaryColor = "#9c27B0";`
to:
`const primaryColor = "#2f2fab";`

But that does not change the primary color on the following parts of the theme:

1. "Tabs with Icons on Card", it stays purple.
2. The shadows beneath all buttons, they stay purple even if I replace all 'rgb' values throughout the theme.
3. Same issue with toggle buttons.
4. The "Login" Landing page.

![img_1494](https://user-images.githubusercontent.com/6205935/39958163-34c0e5d6-55cd-11e8-8c4c-4da15084ff82.JPG)
<img width="949" alt="screen shot 2018-05-12 at 10 07 06 am" src="https://user-images.githubusercontent.com/6205935/39958167-48584d64-55cd-11e8-8983-7516e28d2704.png">
<img width="957" alt="screen shot 2018-05-12 at 10 07 19 am" src="https://user-images.githubusercontent.com/6205935/39958168-4ba8095a-55cd-11e8-8f55-d37db1083c3a.png">
<img width="577" alt="screen shot 2018-05-12 at 10 07 36 am" src="https://user-images.githubusercontent.com/6205935/39958169-4ef5b3e6-55cd-11e8-8c67-723ab9027d5c.png">

**Comment by Sedim** [comment]
Temporary fix:
After some research, I had to change directly wired hex and rgb values in your code in the following files, but there must be a better solution:
<img width="610" alt="screen shot 2018-05-12 at 1 15 45 pm" src="https://user-images.githubusercontent.com/6205935/39959894-a8bbf480-55e6-11e8-9a8c-386688471974.png">

**Comment by EINazare** [comment]
Hello @Sedim ,

Unfortunately, no, there is no other simpler solution.
The thing is that primaryColor only sets the `color` property of a css, not the `box-shadow` too.
So if you want to change both, it is kind of logically that you need to change both in the code too, you can not change one in the code, and automatically the code to change the other one.

Best,
Manu
