### ISSUE TITLE
Material Kit React vs Material UI

### ISSUE THREAD

**Issue by TriStarGod** [creativetimofficial/material-kit-react#45]
I'm confused about the reasoning to choose Material Kit React over Material UI. What advantages does it gain over Material UI?

**Comment by EINazare** [comment]
Hello there @TriStarGod ,

Thank you for your interest in working with our product.
Material-UI only gives you the components necessary to build an app.
We give you a started app in which we use those components, and we restyle some of them.
Hope this information helps you.

Best,
Manu

**Comment by TriStarGod** [comment]
Thanks
