### ISSUE TITLE
class supposed to be called "popperResponsive" - misspelled

### ISSUE THREAD

**Issue by Beamanator** [creativetimofficial/material-kit-react#46]
The following two lines were probably intended to be "popper..." classes, not what they're currently called :)

https://github.com/creativetimofficial/material-kit-react/blob/b715b896a2db5408a072130deb2ba5bef314cee9/src/components/CustomDropdown/CustomDropdown.jsx#L118

https://github.com/creativetimofficial/material-kit-react/blob/b715b896a2db5408a072130deb2ba5bef314cee9/src/assets/jss/material-kit-react/components/customDropdownStyle.jsx#L39

**Comment by EINazare** [comment]
Hello there @Beamanator ,

Thank you for your interest in working with our products and sorry for this late response.
We will address to this issue, in our next update.

Best,
Manu
