### ISSUE TITLE
npm ERR! missing script: build-css

### ISSUE THREAD

**Issue by JackFinnegan** [creativetimofficial/material-kit-react#52]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ ✔] I am running the latest version
- [✔ ] I checked the documentation and found no answer
- [ ✔] I checked to make sure that this issue has not already been filed
- [ ✔] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Run the following in the terminal:
    npm run build

Site then builds.

# Current Behavior

Run the following in the terminal:
    npm run build

And get an error 'npm ERR! missing script: build-css'

# Failure Information (for bugs)
Note, this issue only exists with material-kit-react-v1.4.0. It does not exist with material-kit-react-v1.3.0. The package.json, at least, seems to be different in v1.4.0. Perhaps that has caused this bug?

$ npm run build

TERMINAL OUTPUT from running 'npm run build' in \material-kit-react-v1.4.0 folder:

 > material-kit-react@1.4.0 build C:\Users\Bob\Documents\Repositories\material-kit-react-v1.4.0
 > npm run build-css && react-scripts build

npm ERR! missing script: build-css
npm ERR!
npm ERR! Did you mean this?
npm ERR!     build

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Bob\AppData\Roaming\npm-cache\_logs\2019-02-16T19_34_36_688Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! material-kit-react@1.4.0 build: `npm run build-css && react-scripts build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the material-kit-react@1.4.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Bob\AppData\Roaming\npm-cache\_logs\2019-02-16T19_34_36_703Z-debug.log

-------
OUTPUT OF 2019-02-16T19_34_36_688Z-debug.log:
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build-css' ]
2 info using npm@6.4.1
3 info using node@v10.15.1
4 verbose stack Error: missing script: build-css
4 verbose stack
4 verbose stack Did you mean this?
4 verbose stack     build
4 verbose stack     at run (C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:155:19)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:63:5
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:115:5
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:418:5
4 verbose stack     at checkBinReferences_ (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:373:45)
4 verbose stack     at final (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:416:3)
4 verbose stack     at then (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:160:5)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:280:12
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
5 verbose cwd C:\Users\Bob\Documents\Repositories\material-kit-react-v1.4.0
6 verbose Windows_NT 10.0.17134
7 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build-css"
8 verbose node v10.15.1
9 verbose npm  v6.4.1
10 error missing script: build-css
10 error
10 error Did you mean this?
10 error     build
11 verbose exit [ 1, true ]

-------
OUTPUT OF 2019-02-16T19_34_36_703Z-debug.log:
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@6.4.1
3 info using node@v10.15.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle material-kit-react@1.4.0~prebuild: material-kit-react@1.4.0
6 info lifecycle material-kit-react@1.4.0~build: material-kit-react@1.4.0
7 verbose lifecycle material-kit-react@1.4.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle material-kit-react@1.4.0~build: PATH: -----I have removed these paths from this output------
9 verbose lifecycle material-kit-react@1.4.0~build: CWD: C:\Users\Bob\Documents\Repositories\material-kit-react-v1.4.0
10 silly lifecycle material-kit-react@1.4.0~build: Args: [ '/d /s /c', 'npm run build-css && react-scripts build' ]
11 silly lifecycle material-kit-react@1.4.0~build: Returned: code: 1  signal: null
12 info lifecycle material-kit-react@1.4.0~build: Failed to exec build script
13 verbose stack Error: material-kit-react@1.4.0 build: `npm run build-css && react-scripts build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:189:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:189:13)
13 verbose stack     at maybeClose (internal/child_process.js:970:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid material-kit-react@1.4.0
15 verbose cwd C:\Users\Bob\Documents\Repositories\material-kit-react-v1.4.0
16 verbose Windows_NT 10.0.17134
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v10.15.1
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error material-kit-react@1.4.0 build: `npm run build-css && react-scripts build`
22 error Exit status 1
23 error Failed at the material-kit-react@1.4.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

## Steps to Reproduce

Run the following in the terminal in the \material-kit-react-v1.4.0 folder:
    npm run build

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device: PC
* Operating System: Windows 10

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by EINazare** [comment]
Hello there @BBK-PiJ-2016-85 ,

Thank you for your interest in working with our products.
To solve this, change the build script to:
"build": "react-scripts build"

Best,
Manu

**Comment by BBK-PiJ-2016-85** [comment]
The 'build-css' error now doesn't occur... because I've removed the build-css command as you suggested. But doesn't this mean if I make changes to the scss they will no longer be reflected?

**Comment by EINazare** [comment]
Hello again @BBK-PiJ-2016-85 ,

Yes, they will be reflected since now, we import directly the scss files in the product, instead of the css one.

Best,
Manu

**Comment by BBK-PiJ-2016-85** [comment]
Ok, thanks.

**Comment by atha-github** [comment]
I suggest you please remove the build error and push it in repo.
Thanks.

**Comment by EINazare** [comment]
> I suggest you please remove the build error and push it in repo.
> Thanks.

Hello there @atha-github ,

Thank you for the suggestion.
We'll do on our next update.
At the moment we do not have a timeline for this, and we can't update the product just for this issue, and just on Github, when we update it, we need to make the update on Creative-Tim as well.

Hope you can understand.

Best,
Manu

**Comment by Akkiakabri** [comment]
npm ERR! missing script: build

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Najeebakbari\AppData\Roaming\npm-cache\_logs\2020-09-22T17_45_50_765Z-debug.log
 Hello hope you are doing well could you please help me with this ?

**Comment by rayanduski** [comment]
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path C:\Users\52\Desktop\corse 1/package.json
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\52\Desktop\corse 1\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\52\AppData\Local\npm-cache\_logs\2021-06-06T21_39_31_276Z-debug.log

hello bro i need you're help please
