### ISSUE TITLE
There are multiple modules with names that only differ in casing.

### ISSUE THREAD

**Issue by BBK-PiJ-2016-85** [creativetimofficial/material-kit-react#53]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [✔ ] I am running the latest version
- [✔ ] I checked the documentation and found no answer
- [ ✔] I checked to make sure that this issue has not already been filed
- [✔ ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

npm start should compile without warnings

# Current Behavior

npm start compiles with warnings

# Failure Information (for bugs)

$ npm start

> material-kit-react@1.4.0 start C:\Users\Jack\documents\Repositories\material-kit-react-v1.4.0
> react-scripts start

Starting the development server...

Compiled with warnings.

(webpack)/buildin/global.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* C:\Users\Jack\Documents\Repositories\material-kit-react-v1.4.0\node_modules\react-scripts\node_modules\babel-loader\lib\index.js??ref--6-oneOf-2!C:\Users\Jack\Documents\Repositories\material-kit-react-v1.4.0\node_modules\webpack\buildin\global.js
    Used by 22 module(s), i. e.
    C:\Users\Jack\Documents\Repositories\material-kit-react-v1.4.0\node_modules\react-scripts\node_modules\babel-loader\lib\index.js??ref--6-oneOf-2!C:\Users\Jack\Documents\Repositories\material-kit-react-v1.4.0\node_modules\sockjs-client\lib\entry.js
* C:\Users\Jack\Documents\Repositories\material-kit-react-v1.4.0\node_modules\react-scripts\node_modules\babel-loader\lib\index.js??ref--6-oneOf-2!C:\Users\Jack\documents\Repositories\material-kit-react-v1.4.0\node_modules\webpack\buildin\global.js
    Used by 7 module(s), i. e.
    C:\Users\Jack\Documents\Repositories\material-kit-react-v1.4.0\node_modules\react-scripts\node_modules\babel-loader\lib\index.js??ref--6-oneOf-2!C:\Users\Jack\documents\Repositories\material-kit-react-v1.4.0\node_modules\popper.js\dist\esm\popper.js

(webpack)/buildin/module.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* C:\Users\Jack\Documents\Repositories\material-kit-react-v1.4.0\node_modules\react-scripts\node_modules\babel-loader\lib\index.js??ref--6-oneOf-2!C:\Users\Jack\Documents\Repositories\material-kit-react-v1.4.0\node_modules\webpack\buildin\module.js
    Used by 3 module(s), i. e.
    C:\Users\Jack\Documents\Repositories\material-kit-react-v1.4.0\node_modules\react-scripts\node_modules\babel-loader\lib\index.js??ref--6-oneOf-2!C:\Users\Jack\Documents\Repositories\material-kit-react-v1.4.0\node_modules\node-libs-browser\node_modules\punycode\punycode.js
* C:\Users\Jack\Documents\Repositories\material-kit-react-v1.4.0\node_modules\react-scripts\node_modules\babel-loader\lib\index.js??ref--6-oneOf-2!C:\Users\Jack\documents\Repositories\material-kit-react-v1.4.0\node_modules\webpack\buildin\module.js
    Used by 1 module(s), i. e.
    C:\Users\Jack\Documents\Repositories\material-kit-react-v1.4.0\node_modules\react-scripts\node_modules\babel-loader\lib\index.js??ref--6-oneOf-2!C:\Users\Jack\documents\Repositories\material-kit-react-v1.4.0\node_modules\moment\moment.js

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device:
* Operating System:
* Browser and Version:

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by EINazare** [comment]
Hello there @BBK-PiJ-2016-85 ,

Without making any modifications to this product, this is my output of `npm start`:
<img width="475" alt="screen shot 2019-02-25 at 10 40 41 am" src="https://user-images.githubusercontent.com/26245512/53324646-04783400-38ea-11e9-8df8-a73b225f0aed.png">
<img width="691" alt="screen shot 2019-02-25 at 10 41 00 am" src="https://user-images.githubusercontent.com/26245512/53324648-05a96100-38ea-11e9-9ffa-44e84939ad1d.png">

Can you please detail?

Best,
Manu

**Comment by estaub** [comment]
@BBK-PiJ-2016-85   Jack, if you look carefully at where the only difference in case is between the two names, I think you'll see that the only difference is:  `Jack\documents` vs `Jack\Documents'.  This hints, at least, that you used the wrong case in something.

**Comment by tudtude** [comment]
I was found this errors, it happen when I run `npm start` from visual studio code. It will not happen when run in normal terminal

**Comment by skptricks** [comment]
Is there any solution  ?? getting below message...

D:\sumitprojects\react-beginners>yarn build
yarn run v1.17.3
$ next build
Creating an optimized production build ...

Failed to compile.

./node_modules/fork-ts-checker-webpack-plugin/lib/index.js
Module not found: Can't resolve 'child_process' in 'D:\sumitprojects\react-beginners\node_modules\fork-ts-checker-webpack-plugin\lib'

> Build error occurred
Error: > Build failed because of webpack errors
    at build (D:\sumitprojects\react-beginners\node_modules\next\dist\build\index.js:7:847)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by JackFinnegan** [comment]
> I was found this errors, it happen when I run `npm start` from visual studio code. It will not happen when run in normal terminal

Thanks!

**Comment by yhlchao** [comment]
> I was found this errors, it happen when I run `npm start` from visual studio code. It will not happen when run in normal terminal

This bug bothered me for a long time! Thank you!!

**Comment by jeffscottward** [comment]
I am getting it for both VSCode and terminal.
I have Powerline and OhMyZSH installed.
Whats strange is that its only happening for two modules that existed before I was added to the project.

It's ok for the ones I authored?? so weird
VSCode is noticing something I am not somehow

![Screen Shot 2020-03-18 at 6 22 06 PM](https://user-images.githubusercontent.com/1263486/77012943-61a3b500-6945-11ea-9a76-0f965f3cac73.png)

**Comment by Tribe-Studios** [comment]
I had same issue and for me I had cd'ed into all lower case and not followed case I had used to name directories, once I entered my directories with correct casing I had no issues. I am on Windows 10 LTSB.

**Comment by tienhoangvo** [comment]
I've got that issues too, only because I was using GitBash on windows, GitBash is trying to mimic a linux shell which is case sensitive. When you guys trying to run it with gitBash or vscode default gitbash terminal you guys with get this error. I open cmd and powershell on windows to run the app instead

**Comment by reginpv** [comment]
Replace `import Link from 'next/Link'` to `import Link from 'next/link'`

make L lowercase this was my issue

**Comment by vapx** [comment]
> I've got that issues too, only because I was using GitBash on windows, GitBash is trying to mimic a linux shell which is case sensitive. When you guys trying to run it with gitBash or vscode default gitbash terminal you guys with get this error. I open cmd and powershell on windows to run the app instead

I also tried to run it with cmd in my VS Code. still throwing an error related to compilation warnings this thing bothering more for 2 days lol

**Comment by hellroy** [comment]
Not sure if this was your issue, but I got this same error because I had both Powershell open and VS Code terminal to the same directory. Closing the Powershell window fixed the issue. I think it was forcing some sort of casing.

**Comment by ElbertRibeiro** [comment]
> Não tenho certeza se esse era o seu problema, mas recebi o mesmo erro porque estava com o Powershell aberto e o terminal do VS Code no mesmo diretório. Fechar a janela do Powershell corrigiu o problema. Acho que estava forçando algum tipo de invólucro.

I did the test, run yarn start or npm start using the vscode terminal terminal, maybe it is an error with respect to S.O The same, at the moment, the solution is to use the finish in Vscode.

**Comment by knowuchiha** [comment]
@JackFinnegan  , I guess the problem is related the default path you might be using for VSCode , go there and change it accordingly ,  ex :  documents or Documents,  now even if you do this error will persist because when you created the app , it took the wrong path, refresh vscode create new app and try to run, it will work fine , issue is with the path taken .  I faced the same problem  was using vscode as editor
