### ISSUE TITLE
 need special loader for *.jsx files.

### ISSUE THREAD

**Issue by farshidbakh** [creativetimofficial/material-kit-react#54]
I am using WebStorm, late version and have installed the material-kit-react by issuing:

npm install material-kit-react --save

 I addd the .env file and added the path to that file like"./node_modules/material-kit-react/src" and now I am getting this error: ./node_modules/material-kit-react/src/views/LandingPage/LandingPage.jsx Module parse failed: Unexpected token (29:21) You may need an appropriate loader to handle this file type. | class LandingPage extends React.Component { | render() { | const { classes, ...rest } = this.props; | return ( | <div> 

FYI, I believe Webstorm uses the Babel. I am using the latest React as well. 

This is part of my package.json file:

 "@material-ui/core": "^3.9.2",
    "@material-ui/icons": "^3.0.2",
    "axios": "^0.18.0",
    "highcharts-data": "^0.1.7",
    "highcharts-exporting": "^0.1.7",
    "highcharts-more": "^0.1.7",
    "highcharts-offline-exporting": "^0.1.7",
    "hls.js": "^0.11.0",
    "material-kit-react": "^1.4.0",
    "material-ui": "^0.20.2",
    "material-ui-treeview": "^3.2.0",
    "moment": "^2.24.0",
    "react": "^16.8.4",
    "react-dom": "^16.8.4",
    "react-highcharts": "^16.0.2",
    "react-player": "^1.9.3",
    "react-redux": "^5.1.1",
    "react-router-dom": "^4.3.1",
    "react-scripts": "1.1.1",
    "react-tap-event-plugin": "^3.0.3",
    "redux": "^4.0.1",
    "redux-thunk": "^2.3.0",
    "video-react": "^0.13.3"

The content of my .babelrc file is 
{
  "presets": ["es2015", "stage-0", "react"]
}

I am submitting this issue as it was suggested by einazare (Manu). 

I would truly appreciate your quick action and kind consideration on this matter.

Thanks,
Farshid

**Comment by farshidbakh** [comment]
Hello Manu,

I appreciate your response, and sorry for not using your issue template. I made teh changes you recommended but it didn't change anything. My issue is that it does not know how to load the jsx files. 
This is the error I get 
Failed to compile.
[1] 
[1] ./node_modules/material-kit-react/src/views/LandingPage/LandingPage.jsx
[1] Module parse failed: Unexpected token (29:21)
[1] You may need an appropriate loader to handle this file type.
[1] | class LandingPage extends React.Component {
[1] |   render() {
[1] |     const { classes, ...rest } = this.props;
[1] |     return (
[1] |       <div>

I will continue to search on the net to see if I find anything.  Meanwhile, I appreciate your suggestions as well. 

Thanks,
Farshid

**Comment by EINazare** [comment]
Hello again, @farshidbakh ,

Here is a tutorial made by me, how your webpack config should look like: https://medium.freecodecamp.org/how-to-use-reactjs-with-webpack-4-babel-7-and-material-design-ff754586f618

Please follow the instructions from there.

Best,
Manu

**Comment by farshidbakh** [comment]
Thanks a lot, Manu.  I will take a look at it and let you know if I have any issues. Once again, thanks for your support and quick response!
