### ISSUE TITLE
Any plans for typescript support

### ISSUE THREAD

**Issue by SanthoshDhandapani** [creativetimofficial/material-kit-react#55]
Hi Team,

The work is really awesome, to use it effectively is there any plan for typescript support?

**Comment by EINazare** [comment]
Hello there, @SanthoshDhandapani ,

Thank you for your interest in working with our products.
At the moment we do not plan on using typescript in our products since we are making them using create-react-app (as the official React docs does it).
https://demos.creative-tim.com/material-kit-react/#/documentation/tutorial

Best,
Manu

**Comment by SanthoshDhandapani** [comment]
Hi, 
Thanks for the response team. We knew that create-react-app started to support typescript when we pass typescript param https://facebook.github.io/create-react-app/docs/adding-typescript, so kindly consider this for the future :)

**Comment by bagherani** [comment]
Thanks for producing this awesome kit. If there is any plan for implementing components and theme with typescript it will be very welcomed. Also me myself (and definitely other developers) are open to do this.

**Comment by SanthoshDhandapani** [comment]
Hi @EINazare and @bagherani it's a good news. We migrated this project with react typescript https://github.com/creativetimofficial/material-kit-react/pull/65, my team member https://github.com/Umapreethi-G made a significant contribution on this to bring it live.

**Comment by bentong95923** [comment]
Hi there, I really love the design and was complained that how come there is no typescript version for Material Kit React. I had decided to create a typescript version (and already done) on https://github.com/bentong95923/material-kit-react-typescript. It may be quite scratchy but I would like to help a bit. If the creative tim official is interested you can let me know anytime.
