### ISSUE TITLE
Change color Appbar in Header.jsx

### ISSUE THREAD

**Issue by mariokaram** [creativetimofficial/material-kit-react#58]
# Expected Behavior

I want to change the colors in Header.jsx : defaults are primary, secondary ... 

# Current Behavior

if I choose a specific RGB color or any CSS color it didn't work, 

I tried to use HUE from material UI but also didn't work with react 16+

**Comment by EINazare** [comment]
Hello there, @mariokaram ,

Thank you for your interest in working with our products.
Why didn't you use our whole ISSUES_TEMPLATE?
It would have been nice to know what steps have you taken in trying to change the colors.
The color in our component is set in this file: `src/components/Header/Header.jsx` at line 72:
```
const appBarClasses = classNames({
  [classes.appBar]: true,
  [classes[color]]: color,
  [classes.absolute]: absolute,
  [classes.fixed]: fixed
});
```
Please note:
```
[classes[color]]: color,
```
To change our colors, delete the line above, and then go inside `src/assets/jss/material-kit-react/components/headerStyle.jsx` this file, and at line 24 you will find the background color for this component.

Best,
Manu
