### ISSUE TITLE
CustomInput cannot use onChange

### ISSUE THREAD

**Issue by leonheart1** [creativetimofficial/material-kit-react#6]
```
<CustomInput
          labelText="Username"
          id="username"
          name="username"
          formControlProps={{
                  fullWidth: true
          }}
          onChange={(event) => this.handleChange(event)}
          inputProps={{
                    type: "text",
                    endAdornment: (
                            <InputAdornment position="end">
                                      <People className={classes.inputIconsColor}/>
                            </InputAdornment>
                     )
         }}
/>

handleChange(e) {
        console.log(e);
}
```

this is my code
everytime i tried type on the input, the event not trigger.
can anyone help me ?

**Comment by thucnguyen77** [comment]
Hi,
Could you give an update on how you solved this issue?
Thanks.

**Comment by EINazare** [comment]
Hello @thucnguyen77 ,

Thank you for your interest in using our product.
The only thing to do here is to move the `onChange` property in the `inputProps` property.

Best,
Manu

**Comment by EINazare** [comment]
Hello @fbjerggaard ,

Here is the sample code:
```
<CustomInput
          labelText="Username"
          id="username"
          name="username"
          formControlProps={{
                  fullWidth: true
          }}
          inputProps={{
                    onChange: {(event) => this.handleChange(event)},
                    type: "text",
                    endAdornment: (
                            <InputAdornment position="end">
                                      <People className={classes.inputIconsColor}/>
                            </InputAdornment>
                     )
         }}
/>
```

**Comment by MediaByte** [comment]
Doesn't seem to be working for me.  Screen shot attached.
![screen shot 2018-06-19 at 11 58 33 pm](https://user-images.githubusercontent.com/37881677/41636467-b8e099ac-741c-11e8-8cf1-6e66feb79acc.png)

**Comment by EINazare** [comment]
Hello @mapipina

Thank you for your interest in using our product.
This issue has been already opened here.
Please read the above comments and if the issue still persists, please let me know.

Best,
Manu

**Comment by jarederaj** [comment]
You don't need to wrap the call to the change handler inside of inputProps:

```
inputProps={{
    onChange: this.onChangeEvt
}}
```

**Comment by EINazare** [comment]
Hello there @jarederaj ,

Why would you do not need that?

Best,
Manu

**Comment by iVANWU0522** [comment]
@EINazare Hello, I move the onChange property in the inputProps property. It failed below:
--------------------------------
Failed to compile
Syntax error: Unexpected token (158:37)

  156 |                         }}
  157 |                         inputProps={{
> 158 |                           onChange: {(event) => this.handleChange(event)},
      |                                      ^
  159 |                           placeholder: "Email...",
  160 |                           type: "email",
  161 |                           startAdornment: (

**Comment by EINazare** [comment]
Hello there @iVANWU0522 ,

Can you paste the whole CustomInput here?

Best,
Manu

**Comment by iVANWU0522** [comment]
@EINazare 
---------------------
<CustomInput
                        id="pass"
                        formControlProps={{
                          fullWidth: true
                        }}
                        inputProps={{
                          onChange: {(event) => this.handleChange(event)},
                          placeholder: "Password",
                          type: "password",
                          startAdornment: (
                            <InputAdornment position="start">
                              <Icon className={classes.inputIconsColor}>
                                lock_utline
                              </Icon>
                            </InputAdornment>
                          )
                        }}
                      />

**Comment by EINazare** [comment]
Hello there @iVANWU0522 ,

Can you try:
```
                  <CustomInput
                    id="pass"
                    formControlProps={{
                      fullWidth: true
                    }}
                    inputProps={{
                      onChange: (event) => this.handleChange(event),
                      placeholder: "Password",
                      type: "password",
                      startAdornment: (
                        <InputAdornment position="start">
                          <Icon className={classes.inputIconsColor}>
                            lock_utline
                          </Icon>
                        </InputAdornment>
                      )
                    }}
                  />
```

I believe that by sending the function between brackets, you are actually sending an object, instead of a function.

Best,
Manu

**Comment by jarederaj** [comment]
> Hello there @jarederaj ,
> 
> Why would you do not need that?
> 
> Best,
> Manu

The code passes a function vs passing an object. Use typeof() to see the difference.

**Comment by brunerfilgueiras** [comment]
Hello there @iVANWU0522 ,

Can you try:

                  <CustomInput
                    id="pass"
                    formControlProps={{
                      fullWidth: true
                    }}
                    inputProps={{
                      onChange: (event) => this.handleChange(event.target.value),
                      placeholder: "Password",
                      type: "password",
                      startAdornment: (
                        <InputAdornment position="start">
                          <Icon className={classes.inputIconsColor}>
                            lock_utline
                          </Icon>
                        </InputAdornment>
                      )
                    }}
                  />

**Comment by andrew-ha** [comment]
I'm not sure how to do this, getting error:  Cannot read property 'handleChange' of undefined
`
function handleChange(e) {
  console.log(e);
}

export default function ContactMe() {
  return (
    <CustomInput
      labelText="Email Body"
      id="font-awesome"
      formControlProps={{
        fullWidth: true
      }}
      multiline={true}
      inputProps={{
        onChange: (e) => this.handleChange(e),
        endAdornment: (
          <InputAdornment position="end">
            <i className="fas fa-envelope" />
          </InputAdornment>
        )
      }}
    />
  )
}
`
Any clue as to how to implement this?

**Comment by EINazare** [comment]
Hello there, @andrew-ha ,

You have the following code:
```
onChange: (e) => this.handleChange(e),
```
And you are getting an error
```
 Cannot read property 'handleChange' of undefined
```
Meaning, that `this` is not defined. So I guess the solution to your use case would be to change the above code to:
```
onChange: (e) => handleChange(e),
```

Best,
Manu

**Comment by monscamus** [comment]
It's important to note if you are doing this in a Functional component or React Class component. That's why some will not the "this" and the arrow operator is enough.
