### ISSUE TITLE
I can not update Material UI? error npm run build

### ISSUE THREAD

**Issue by marcossk8** [creativetimofficial/material-kit-react#60]
When I update Material UI, I can not run npm run build.

Failed to minify the bundle. Error: static/js/main.241a8428.js from UglifyJs
RangeError: Maximum call stack size exceeded

**Comment by marcossk8** [comment]
package.json:
{
  "name": "material-kit-react",
  "version": "1.3.0",
  "private": true,
  "main": "dist/index.js",
  "dependencies": {
    "@material-ui/core": "^4.1.2",
    "@material-ui/icons": "^4.1.0",
    "classnames": "2.2.6",
    "firebase": "^6.2.2",
    "history": "4.7.2",
    "moment": "2.22.2",
    "node-sass-chokidar": "1.3.3",
    "nouislider": "12.0.0",
    "npm-run-all": "4.1.3",
    "prop-types": "15.6.2",
    "react": "^16.8.0",
    "react-datetime": "2.15.0",
    "react-dom": "^16.8.0",
    "react-router-dom": "4.3.1",
    "react-scripts": "1.1.5",
    "react-slick": "0.23.1",
    "react-swipeable-views": "0.13.0"
  },
  "devDependencies": {
    "babel-cli": "6.26.0",
    "babel-plugin-module-resolver": "3.1.1",
    "babel-plugin-import-rename": "1.0.1",
    "babel-plugin-transform-object-rest-spread": "6.26.0",
    "babel-plugin-transform-react-jsx": "6.24.1",
    "babel-preset-es2015": "6.24.1"
  },
  "optionalDependencies": {
    "ajv": "5.0.0",
    "babel-eslint": "7.2.3",
    "eslint": "4.19.1",
    "eslint-config-prettier": "3.1.0",
    "eslint-plugin-prettier": "2.6.2",
    "eslint-plugin-react": "7.11.1",
    "prettier": "1.14.3"
  },
  "scripts": {
    "build-css": "node-sass-chokidar --include-path ./src --include-path ./node_modules src/ -o src/",
    "watch-css": "npm run build-css && node-sass-chokidar --include-path ./src --include-path ./node_modules src/ -o src/ --watch --recursive",
    "start-js": "react-scripts start",
    "start": "npm-run-all -p watch-css start-js",
    "build": "npm run build-css && react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject",
    "lint:check": "eslint . --ext=js,jsx;  exit 0",
    "lint:fix": "eslint . --ext=js,jsx --fix;  exit 0",
    "install:clean": "rm -rf node_modules/ && rm -rf package-lock.json && npm install && npm start",
    "build-package-css": "node-sass-chokidar src/assets/scss/material-kit-react.scss dist/material-kit-react.css",
    "build-package": "npm run build-package-css && babel src --out-dir dist"
  }
}

**Comment by EINazare** [comment]
This issue was closed due to the fact that it did not meet our rules:
```
<!--
 IMPORTANT: Please use the following link to create a new issue:

  https://www.creative-tim.com/new-issue/material-kit-react

**If your issue was not created using the app above, it will be closed immediately.**
-->

<!--
Love Creative Tim? Do you need Angular, React, Vuejs or HTML? You can visit:
👉  https://www.creative-tim.com/bundles
👉  https://www.creative-tim.com
-->

```
