### ISSUE TITLE
[Feature Request] Typescript support is broken

### ISSUE THREAD

**Issue by davidLeonardi** [creativetimofficial/material-kit-react#63]
### What is your enhancement?
I am including material-kit-react as an NPM module into my typescript react project.

I am unable to import any of the modules, because dist/index.js does not export any of the components.
I am unable to import any of the modules by directly importing them either, because there are not type definitions for the components.
Furthermore, after hacking around a bit, some components such as Button appear to be broken due to incorrect type inference.

As a react developer who uses Typescript I would love to have typescript type definitions bundled with this amazing UI toolkit, and a distribution which allows me to import the components directly using imports.

**Comment by EINazare** [comment]
Hello there, @davidLeonardi ,

Thank you for your interest in working with our products.
Please use our kit as described here: https://github.com/creativetimofficial/ct-material-dashboard-pro-react/issues/50#issuecomment-407030675
At the moment we are not going to add TypeScript to any of our React products.

Best,
Manu
