### ISSUE TITLE
Your Package Can't Be Imported

### ISSUE THREAD

**Issue by machineghost** [creativetimofficial/material-kit-react#66]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Every package in NPM works the same basic way:

    const package = require('package-name');

However, if you try to require your package:

> > require('material-kit-react')
> Thrown:
> Error: Cannot find module '/home/me/projects/some-project/node_modules/material-kit-react/dist/index.js'. Please verify that the package.json has a valid "main" entry
>     at tryPackage (internal/modules/cjs/loader.js:264:19)
>     at Function.Module._findPath (internal/modules/cjs/loader.js:456:18)
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:700:27)
>     at Function.Module._load (internal/modules/cjs/loader.js:618:27)
>     at Module.require (internal/modules/cjs/loader.js:771:19)
>     at require (internal/modules/cjs/helpers.js:68:18) {
>   code: 'MODULE_NOT_FOUND',
>   path: '/home/me/projects/some-project/node_modules/material-kit-react/package.json',
>   requestPath: 'material-kit-react'
> 

# Current Behavior

All of the import lines in your React documentation are for paths like:

    import Button from 'components/CustomButtons/Button.jsx';

*Obviously* these are invalid Node paths, but to be clear I tried anyway, and they don't work either:

>  > require('components/CustomButton/Button.jsx')
> Thrown:
> Error: Cannot find module 'components/CustomButton/Button.jsx'
> Require stack:
> - <repl>
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:713:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:618:27)
>     at Module.require (internal/modules/cjs/loader.js:771:19)
>     at require (internal/modules/cjs/helpers.js:68:18) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [ '<repl>' ]
> }

## Steps to Reproduce

1. npm i material-kit-react (just like any other NPM package)
2. visit https://demos.creative-tim.com/material-kit-react/#/documentation/buttons OR just do the obvious `require('material-kit-react')`
3. be confused

## Context

Virtually every React developer (certainly every one that uses create-react-app) ... and hell, every Node user, will expect to be able to import/require a node package.  I was super excited to try your great Material UI widgets, but on a technical level it's scary that it isn't following the basics of all Node packages.

**Comment by machineghost** [comment]
P.S. The core problem is that line 122 of your `package.json` is `"main": "dist/index.js",`.  However your package doesn't even have a `dist/index.js` file.

It does have a `src/index.js`, which does import several files from your library:

```
import Components from "views/Components/Components.js";
import LandingPage from "views/LandingPage/LandingPage.js";
import ProfilePage from "views/ProfilePage/ProfilePage.js";
import LoginPage from "views/LoginPage/LoginPage.js";
```
... but then it doesn't export them, it just uses them in an example.

Your dist/index.js should import every file in your library, and then export them as either named or (in one case) default exports.  For instance:

```
export { Components, LandingPage,  ProfilePage, LoginPage };
```

**Comment by EINazare** [comment]
Hello there, @machineghost ,

We will take a look at this on some next updates. Right now we are stuck on creating new templates.
Meanwhile, please take a look at this issue: https://github.com/creativetimofficial/ct-material-dashboard-pro-react/issues/50#issuecomment-407030675

Best,
Manu

**Comment by owlcode** [comment]
Is Merge Request welcomed?

**Comment by EINazare** [comment]
Hello there, @owlcode ,

At the moment we do not have a procedure for this.
We'll discuss it with my superiors.

Best,
Manu

**Comment by qhenkart** [comment]
@einazare What is the general use purpose of this kit. Are your customers and users expected to always start with cloning your repo and then thinning it down and replacing content until it matches their needs? I don't fully understand the product in light of this unresolved issue.

**Comment by sajadevo** [comment]
**Hi there**

We've updated the product to v2.0.0 and now it contains a totally new structure with a new and fresh design.

**All the best**
**Sajad**
