### ISSUE TITLE
[Bug] Error after `npm i` TypeError: Cannot read property 'type' of undefined 

### ISSUE THREAD

**Issue by johnandblue** [creativetimofficial/material-kit-react#67]
### Version
material kit react 1.8.0
### Reproduction link
https://github.com/johnandblue/material-kit-react
### Operating System
node 12.2.0
### Device
Mac OSX
### Browser & Version
Any
### Steps to reproduce
Clone the material kit react from `https://github.com/creativetimofficial/material-kit-react`
run `npm i` or `npm run install:clean`
run `npm start`

### What is expected?
render the route `/` page using the component located in:
`/src/views/Components/Components.js`
### What is actually happening?
Getting this error:
```
Failed to compile
./src/views/Components/Components.js
TypeError: Cannot read property 'type' of undefined
Occurred while linting /Users/jc/Desktop/dev/material-kit-react/src/views/Components/Components.js:38
    at Array.forEach (<anonymous>)
    at Array.forEach (<anonymous>)
```

---

**Comment by EINazare** [comment]
Hello there, @johnandblue ,

Thank you for your interest in working with our products.
Please install NodeJS version 10.16.3 LTS.
The NodeJS Version Current (12.2.0) comes with a lot of bugs.

Let me know if that was the issue.

Best,
Manu

**Comment by johnandblue** [comment]
Hi @EINazare,

I changed the node version but didn't work.
NodeJS: v.10.16.3
NPM v.6.9.0

Here is an screenshot with some more detail on the error I'm getting on the browser:
<img width="1677" alt="Screenshot 2019-09-30 at 14 28 02" src="https://user-images.githubusercontent.com/21159524/65878718-f5c99200-e38e-11e9-96be-62d73b4a6320.png">

**Comment by EINazare** [comment]
Hello again, @johnandblue ,

Thank you for your interest in working with our products.
This is actually an error from the react-scripts package, here is the link to the mentioned issue: https://github.com/facebook/create-react-app/issues/7753
To solve the issue, please run the following: `npm i -E eslint@6.4.0`.

Best,
Manu

**Comment by johnandblue** [comment]
@EINazare, 

Now works like a charm! definitely saving exact made the trick. 
Many thanks for the fast answers!
