### ISSUE TITLE
[Bug] Gulpfile.js Pointing to Now UI Pro kit Instead of Material kit React 

### ISSUE THREAD

**Issue by snitin315** [creativetimofficial/material-kit-react#68]
### Version
1.8.0
### Reproduction link
https://github.com/creativetimofficial/material-kit-react
### Operating System
Kali Linux
### Device
Lenovo Ideapad 330s
### Browser & Version
Google Chrome
### Steps to reproduce
1. visit the official github repo https://github.com/creativetimofficial/material-kit-react
2. open the gulpfile.js
3. see its pointing to NOW UI Pro kit instead of Material kit react 

### What is expected?
Expected to have the name of Material kit React and link to its product page
### What is actually happening?
Showing name of Now UI kit and link to its product page instead of  Material kit react.

---
### Solution
Replace the name and product page link from Now UI kit  to Material Kit React
### Additional comments
I have fixed the bug and will sent a Pull Request regarding this.

**Comment by EINazare** [comment]
Hello there, @snitin315 ,

Thank you for your interest in working with our products.
Can you make the PR to point to the customer-support branch? (https://github.com/creativetimofficial/material-kit-react/tree/customer-support)

Best,
Manu

**Comment by snitin315** [comment]
Hello @EINazare,  the customer-support branch doesn't seem to have the gulpfile.js file . Should I add it and make a PR then?

**Comment by EINazare** [comment]
Hello again, @snitin315 ,

Yes, that would be great.
I hope I'll have time by the end of this year to merge the customer-support branch into the master one.

Best,
Manu

**Comment by snitin315** [comment]
@EINazare All Done. I have sent PR to point to customer-support branch #70
