### ISSUE TITLE
Module not found using npm

### ISSUE THREAD

**Issue by richburdon** [creativetimofficial/material-kit-react#71]
I get an error when trying to import the module.

```
Module not found: Error: Can't resolve 'material-kit-react' in 'website/src/components'
```

It also fails via the runkit link on your npm page:

https://npm.runkit.com/material-kit-react

Looking in node_modules, seems like you might have run npm publish without building the dist package?

**Comment by EINazare** [comment]
Hello there, @richburdon ,

Thank for your issue.
Until we solve this, please download the product and use it like so.
Also, you could check this thread here: https://github.com/creativetimofficial/ct-material-dashboard-pro-react/issues/50#issuecomment-407030675

Best,
Manu

**Comment by edenlin18** [comment]
Hi @EINazare,
Really appreciate your guys' efforts in making such a great material-ui library!
Any idea of when a new version will be published that fixes this issue?
Also, will the pro version be available via npm soon too?

Thanks!

**Comment by EINazare** [comment]
Hello again, @edenlin18 ,

We'll try to release the new versions for all of our Material & React products by 15th of March.
The npm distribution for the pro products was postponed, and we do not have a timeline for this.

Best,
Manu

**Comment by sajadevo** [comment]
**Hi there**

We've updated the product to v2.0.0 and now it contains a totally new structure with a new and fresh design.

**All the best**
**Sajad**
