### ISSUE TITLE
React Native app is crashing in IOS after adding a style in JSX

### ISSUE THREAD

**Issue by maityutpal** [creativetimofficial/material-kit-react#73]
I am building app and creating a component with the following JSX markup and the APP is crashing in IOS but working in Android.

`<Block row space="between" style={{ paddingVertical: 16, alignItems: 'baseline' }}>
            <Block row space="between" style={{ paddingVertical: 16, alignItems: 'baseline' }}>
                <Text size={18}>Quantity:</Text> 
                <Input style={{ borderRadius: 3, borderColor: materialTheme.COLORS.INPUT,width:60,height:30 }} /> 
            </Block> `

But it is working with the below markup perfectly if I remove the style property.And the

`<Block row space="between" style={{ paddingVertical: 16, alignItems: 'baseline' }}>
            <Block row space="between">
                <Text size={18}>Quantity:</Text> 
                <Input style={{ borderRadius: 3, borderColor: materialTheme.COLORS.INPUT,width:60,height:30 }} /> 
            </Block> `

**Comment by EINazare** [comment]
Hello there, @maityutpal ,

I am a bit confused about your comment.
Firstly, you did not follow our rules:
```
<!--
 IMPORTANT: Please use the following link to create a new issue:

  https://www.creative-tim.com/new-issue/material-kit-react

**If your issue was not created using the app above, it will be closed immediately.**
-->

<!--
Love Creative Tim? Do you need Angular, React, Vuejs or HTML? You can visit:
👉  https://www.creative-tim.com/bundles
👉  https://www.creative-tim.com
-->
```
Secondly, you have opened an issue on the Material Kit React repository, which is a ReactJS product, not a React Native product.

Please provide a link to the product that you are using and I will redirect you to its repository if it is a Creative Tim product.

Best,
Manu
