### ISSUE TITLE
[Bug] Cannot use imported classes when using React.Component instead of exported function

### ISSUE THREAD

**Issue by joepagan** [creativetimofficial/material-kit-react#78]
### Version
1.8.0
### Reproduction link
https://github.com/dont-have-one-because-probably-simple-solution-and-im-new
### Operating System
macos
### Device
macbook
### Browser & Version
firefox
### Steps to reproduce
Hey, thanks for your work on this.

I have had to make a component by extending `React.Component` so I can use `componentDidMount` rather than using the exported function method which is used throughout your app.

Now I have done this I cannot seem to apply my styles, as I keep running into errors with the way they are imported or whereever I attempt to use them.

I'm new to React and not sure how to deal with this in this scenario, code example:
```
import React from "react";
import { makeStyles } from "@material-ui/core/styles";
import styles from "assets/jss/material-kit-react/views/componentsSections/showsStyle.js";
class SectionShows extends React.Component {
  constructor(props) {
    super(props);
  }
  componentDidMount() {
console.log('mount')
  }
  render() {
    const useStyles = makeStyles(styles);
    const classes = useStyles();
    return (
      <div id="shows" className={classes.section}>
         ...
```
### What is expected?
no react errors
### What is actually happening?
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.

---

**Comment by EINazare** [comment]
Hello there @joepagan ,

To use Class Components, you need to change the usage of `makeStyles` (delete everything that has to do with this function), and import `withStyles` from material-ui, instead of it, and then in the export statement of your component, you need to add:
```
export default withStyles(styles)(YourComponent);
```
Full example:
```
import React from "react";
import { withStyles } from "@material-ui/core/styles";
import styles from "assets/jss/material-kit-react/views/componentsSections/showsStyle.js";
class SectionShows extends React.Component {
  constructor(props) {
    super(props);
  }
  componentDidMount() {
        console.log('mount')
  }
  render() {
      const { classes } = this.props;
     // delete these lines
    // const useStyles = makeStyles(styles);
    // const classes = useStyles();
    return (
         ...
    );
  }
}

export default withStyles(styles)(SectionShows);
```

Best,
Manu

**Comment by joepagan** [comment]
Thanks for the explanation @EINazare that's very kind of you. All sorted now thanks.
