### ISSUE TITLE
[Feature Request] TypeScript version created, may you consider it?

### ISSUE THREAD

**Issue by bentong95923** [creativetimofficial/material-kit-react#82]
### What is your enhancement?
Hi there, I really love the design and was quite frustrated that how come there is no typescript version for Material Kit React. I had decided to create a typescript version (and already done) on https://github.com/bentong95923/material-kit-react-typescript. It may be quite scratchy but I would like to help a bit. If the creative tim official is interested feel free to let me know anytime.

Sorry if it is not the correct way to make a contribution. I had considered a Pull Request yet it is a separate version and cannot be merged. Hence, I created an issue.

Thanks <3

**Comment by sajadevo** [comment]
**Hi there**

We've updated the product to v2.0.0 and now it contains a totally new structure with a new and fresh design.

**All the best**
**Sajad**

**Comment by rickstaa** [comment]
@sajadevo Thanks for the update. I think the v2 pro version is a lot cleaner and solves a lot of the issues I had with version 1! Thanks a lot. I updated my rating from 2 to 4 stars. I was about to give a 5-star rating but then I saw there is still no typescript version.

**Comment by sajadevo** [comment]
**Hi @rickstaa **

Thanks for your kind words, unfortunately for now it doesn't support TypeScript but within a month there will be TypeScript support as well I'm working on it.


**All the best
Sajad**

**Comment by rickstaa** [comment]
Amazing! Looking forward to the release.

**Comment by bentong95923** [comment]
Finally! Can't wait! 

> **Hi @rickstaa **
> 
> Thanks for your kind words, unfortunately for now it doesn't support TypeScript but within a month there will be TypeScript support as well I'm working on it.
> 
> **All the best Sajad**

**Comment by keulenIT** [comment]
Hi @sajadevo is typescript support already present? And is it limited to a specific version?
