### ISSUE TITLE
[Bug] Header Socials and social tooltips for Socials are not showing up 

### ISSUE THREAD

**Issue by lemarcgagnon** [creativetimofficial/material-kit-react#85]
### Version
latest and online demo as well
### Reproduction link
https://demos.creative-tim.com/material-kit-react
### Operating System
linux
### Device
desktop
### Browser & Version
Version 86.0.4240.75 (Official Build) (64-bit)
### Steps to reproduce
why is these three lines don't show up either on your online demo and on the version I downloaded:  These are part of the header?

<li class="MuiListItem-root jss42 MuiListItem-gutters"><a class="MuiButtonBase-root MuiButton-root MuiButton-text jss73 jss87 jss44" tabindex="0" aria-disabled="false" href="https://twitter.com/CreativeTim?ref=creativetim" target="_blank" title="Follow us on twitter"><span class="MuiButton-label"><i class="jss49 fab fa-twitter"></i></span><span class="MuiTouchRipple-root"></span></a></li>

This is located in Components:Header: HeaderLinks.js

<ListItem className={classes.listItem}>
        <Tooltip
          id="instagram-facebook"
          title="Follow us on facebook"
          placement={window.innerWidth > 959 ? "top" : "left"}
          classes={{ tooltip: classes.tooltip }}
        >
          <Button
            color="transparent"
            href="https://www.facebook.com/CreativeTim?ref=creativetim"
            target="_blank"
            className={classes.navLink}
          >
            <i className={classes.socialIcons + " fab fa-facebook"} />
          </Button>
        </Tooltip>
      </ListItem>

Could it be the class messing it up?     ==>  classes={{ tooltip: classes.tooltip }}

It won't show either in full and responsive window size.
### What is expected?
to see the social buttons and the tooltips since the showup in the source code
### What is actually happening?
not showing up in chrome, but I see it on Firefox 81.0 on Mint Linux

---
### Solution
maybe it is the classes setup

**Comment by EINazare** [comment]
Hello there, @lemarcgagnon ,

Those lines are for the Tooltips that appear when you hover the Twitter, Facebook and Instagram icons.

Best,
Manu

**Comment by lemarcgagnon** [comment]
great sure, I knew that, but they don't show up for chrome Linux Version
86.0.4240.75 (Official Build) (64-bit)

Yours,

MArc

**Comment by dtksi** [comment]
you should import
```
import FacebookIcon from '@material-ui/icons/Facebook';
```
then `<FacebookIcon />` instead of `<i className={classes.socialIcons + " fab fa-facebook"} />`

**Comment by lemarcgagnon** [comment]
Thanks for the tip!
