### ISSUE TITLE
[Bug] Navigation Pills Don't Animate on the first Click

### ISSUE THREAD

**Issue by johnboy36** [creativetimofficial/material-kit-react#86]
### Version
Current
### Reproduction link
https://demos.creative-tim.com/material-kit-pro-react/#/components
### Operating System
Win 10
### Device
Desktop
### Browser & Version
Chrome 86 and Edge
### Steps to reproduce
Click the Navigation Pill labelled 'Settings', the content appears and doesn't slide in.
Click 'Profile', the content arrives via slide in animation.
Click 'Settings', the content arrives via slide in animation.
### What is expected?
The settings content should slide in with an animation
### What is actually happening?
on the first click, it just appears

---

**Comment by EINazare** [comment]
Hello @johnboy36 ,

Thank you for your interest in working with our products.
We know about this issue, but we do not know how to solve it, unfortunately.
If you have any solution, we are more than happy to listen to suggestions.

Best,
Manu

**Comment by johnboy36** [comment]
Hi Manu,

I would normally ask for a refund if I paid for a product, then found out it had a fault and the makers didn't know how to fix the fault.
Imagine if you built cars instead of web frameworks!

Thanks

John

________________________________
