### ISSUE TITLE
[Feature Request] OnChange is not working on CustomInput

### ISSUE THREAD

**Issue by Ktrist** [creativetimofficial/material-kit-react#87]
### What is your enhancement?
Hello All, 
I'm using the landing page Login Template, i've connect to my database ( works fine with postman) but wen i try to make it works with the Onchange on a custom Input field nothing is happening. 
Do you know how i can make Onchange and Onclick (event handler) on custom Input working ? 
Best,

**Comment by shumbaashley** [comment]
Any fixes on this issue yet? I am facing the same problem.

**Comment by maratha1205** [comment]
Have you got the solution?
