### ISSUE TITLE
[Bug] smoothScroll function not working properly in HeaderLinks.js

### ISSUE THREAD

**Issue by Bgjones15** [creativetimofficial/material-kit-react#95]
### Version
v1.10.0
### Reproduction link
https://demos.creative-tim.com/material-kit-pro-react/
### Operating System
Windows 10
### Device
PC
### Browser & Version
Chrome 91.0.4472.114
### Steps to reproduce
Go to https://demos.creative-tim.com/material-kit-pro-react/
Click Sections -> Projects
### What is expected?
Goes to /sections then scrolls to element with ID projects.
### What is actually happening?
Blank white page, refreshing page is just at the top of the sections page.

---

**Comment by sajadevo** [comment]
**Hi there**

We've updated the product to v2.0.0 and now it contains a totally new structure with a new and fresh design.

**All the best**
**Sajad**
