### ISSUE TITLE
[Bug] No links work on downloaded package

### ISSUE THREAD

**Issue by kFuQ** [creativetimofficial/material-kit-react#96]
### Version
  "version": "1.10.0",
### Reproduction link
http://1x.getit.wtf:3000
### Operating System
win10
### Device
laptop
### Browser & Version
Brave  Version 1.33.106 Chromium: 96.0.4664.110 (Official Build) (64-bit)
### Steps to reproduce
unzip downloaded package, install w/ npm run install:clean
no urls work, demo links on Components page disabled too.

it works find on the CT website.
### What is expected?
URLs to work
### What is actually happening?
URLS dont work

---
### Solution
ask for help to see why urls dont work from the downloaded package
### Additional comments
Thanks!

**Comment by sajadevo** [comment]
**Hi there**

We've updated the product to v2.0.0 and now it contains a totally new structure with a new and fresh design.

**All the best**
**Sajad**
